application/account/routes.py
import os

from flask import Blueprint
from flask_login import login_required

import application.account.controller as controller

template_dir = os.path.abspath('../templates')
account_blueprint = Blueprint('account', __name__, url_prefix='/account', template_folder=template_dir)


@account_blueprint.route('/account/<user_id>', methods=['GET', 'POST'])
@login_required
def show_account(user_id):
    controller.show_account(user_id)


@account_blueprint.route('/my-account', methods=['GET', 'POST'])
@login_required
def show_my_account():
    return controller.show_my_account()

application/ad/routes.py
import os

from flask import Blueprint
from flask_login import login_required

import application.ad.controller as controller
from application.admin import is_owner

template_dir = os.path.abspath('../templates')
ad_blueprint = Blueprint('ad', __name__, url_prefix='/ad', template_folder=template_dir)


@ad_blueprint.route('/create-ad', methods=['GET', 'POST'])
@login_required
def create_ad():
    return controller.create_ad()


@ad_blueprint.route('/<ad_id>')
@login_required
def show_ad(ad_id):
    return controller.show_ad(ad_id)


@ad_blueprint.route('/<ad_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_ad(ad_id):
    return controller.edit_ad(ad_id)


@ad_blueprint.route('/<ad_id>/delete')
@login_required
def delete_ad(ad_id):
    return controller.delete_ad(ad_id)


@ad_blueprint.route('/<link_id>/delete_ad_photo')
@login_required
def delete_ad_photo(link_id):
    return controller.delete_ad_photo(link_id)

application/main/routes.py
import os

from flask import Blueprint, render_template, request

from application.models import Ad
from application.models import Categories


template_dir = os.path.abspath('../templates')
main_blueprint = Blueprint('main', __name__, template_folder=template_dir)


@main_blueprint.route('/')
def index():
    search = request.args.get('search')
    categories = request.args.getlist('category')
    page = request.args.get('page')
    ads = Ad.query.order_by(Ad.created_at.desc())
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if search:
        found = "%{}%".format(search)
        ads = Ad.query.filter(
            Ad.title.like(found) |
            Ad.category.like(found) |
            Ad.description.like(found)
        ).order_by(Ad.created_at.desc())

    if categories:
        ads = Ad.query.filter(
            Ad.category.in_(categories)
        )
    pages = ads.paginate(page=page, per_page=5)

    return render_template('main/main.html', title='Index',
                           ads=ads, categoryes=Categories, pages=pages)

application/templates/layout.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
        <link rel="stylesheet" href="../static/main.css">
        <style>
            html {height: 100%;}
            body {height: 100%;}
            .alert-wrap {
              position: absolute;
              margin-top: 2%;
              margin-left: 33%;
              width: 33%;
              animation: alert 3s linear none;
              opacity: 0;
              transition: all .3s ease-in-out;
            }

            @keyframes alert {
              0%,
              100% {
                opacity: 0;
              }
              10% {
                opacity: 1;
              }
              90% {
                opacity: 1;
              }
            }

            .alert_wrap:hover {
              opacity: 1;
            }
        </style>
    </head>
    {% include 'navbar.html' %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger alert-wrap">{{ message }}</div>
    {% endfor %}
    <div class="container mt-3 h-100">
        {% block content %}{% endblock %}
    </div>
</html>

application/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Metathesis</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                </li>
            {% endif %}

            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.sign_out') }}">Sign Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('account.show_my_account') }}">
                        User: {{ current_user.username }} (Role: {{ current_user.role.value }})
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('ad.create_ad') }}">Create ad</a>
                </li>
                {% if current_user.role.name == 'admin' %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                    {% endif %}
                </li>

            {% endif %}
        </ul>
    </div>
</nav>