application/ad/controller.py
import os

from flask import render_template, redirect, url_for, request, flash, abort
from flask_login import current_user
from werkzeug.utils import secure_filename

from application import db
from application.ad.form import AdForm
from application.ad.utils import check_size, resize_image, allowed_file, save_file_in_static
from application.admin import is_owner
from application.models import Ad, AdPhoto, Categories


def save_ad(new_ad, files):
    db.session.add(new_ad)
    db.session.commit()
    upload_photo(new_ad.id, files)


def create_ad():
    form = AdForm()
    form.category.choices = Categories
    if request.method == 'POST':
        files = request.files.getlist('file')
        print(form.connection.data, "CONNECTION", flush=True)
        new_ad = Ad(
            form.title.data,
            form.category.data,
            form.description.data,
            form.connection.data,
            current_user.id
        )
        save_ad(new_ad, files)
        return redirect(url_for('ad.show_ad', ad_id=new_ad.id))
    return render_template('ad/creating.html', title='Creating ad', form=form)


def upload_photo(ad_id, files):
    upload_folder = "application/static/uploads/"
    for file in files:
        print(file, flush=True)
        if file and allowed_file(file.filename):
            file_name = secure_filename(file.filename)
            if check_size(file) > 1024 * 1024 + 1:
                file = resize_image(file)
            try:
                path = os.path.join(upload_folder, str(ad_id))
                os.mkdir(path)
                save_file_in_static(file, file_name, str(ad_id))
            except FileExistsError:
                save_file_in_static(file, file_name, str(ad_id))
            finally:
                file_path = '/uploads/' + str(ad_id) + '/' + file_name
                photo = AdPhoto(file_path, ad_id)
                db.session.add(photo)
                db.session.commit()


def show_ad(ad_id):
    ad = Ad.query.get(ad_id)
    return render_template('ad/show_ad.html', ad=ad, photos=ad.ad_photos, user=ad.user)


def edit_ad(ad_id):
    ad = Ad.query.get(ad_id)
    is_owner(ad)
    form = AdForm(request.form, obj=ad)
    form.category.choices = Categories
    if request.method == 'POST':
        files = request.files.getlist('file')
        form.populate_obj(ad)
        upload_photo(ad.id, files)
        db.session.commit()
        return render_template('ad/show_ad.html', ad=ad, photos=ad.ad_photos, user=ad.user)
    return render_template('ad/edit_ad.html', ad=ad, form=form)


def delete_ad(ad_id):
    ad = Ad.query.get(ad_id)
    is_owner(ad)
    db.session.delete(ad)
    db.session.commit()
    flash(f'The project {ad.title} has been deleted')
    return redirect(url_for('main.index'))


def delete_ad_photo(link_id):
    photo = AdPhoto.query.get(link_id)
    is_owner(photo.ad)
    tmp = photo.ad.id
    db.session.delete(photo)
    db.session.commit()
    flash(f'Photo has been deleted')
    return redirect(url_for('ad.edit_ad', ad_id=tmp))

application/ad/routes.py
import os

from flask import Blueprint
from flask_login import login_required

import application.ad.controller as controller
from application.admin import is_owner

template_dir = os.path.abspath('../templates')
ad_blueprint = Blueprint('ad', __name__, url_prefix='/ad', template_folder=template_dir)


@ad_blueprint.route('/create-ad', methods=['GET', 'POST'])
@login_required
def create_ad():
    return controller.create_ad()


@ad_blueprint.route('/<ad_id>')
@login_required
def show_ad(ad_id):
    return controller.show_ad(ad_id)


@ad_blueprint.route('/<ad_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_ad(ad_id):
    return controller.edit_ad(ad_id)


@ad_blueprint.route('/<ad_id>/delete')
@login_required
def delete_ad(ad_id):
    return controller.delete_ad(ad_id)


@ad_blueprint.route('/<link_id>/delete_ad_photo')
@login_required
def delete_ad_photo(link_id):
    return controller.delete_ad_photo(link_id)

application/templates/ad/creating.html
{% extends "layout.html" %}

{% block content %}

    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <h1 class="h3 mb-3 fw-normal text-center">Create new ad</h1>

                <div class="form-floating mb-3">
                    <input type="text" name="title" class="form-control" id="title" placeholder="title">
                    <label for="title">Title</label>
                </div>

                <div class="form-floating mb-3">
                    <select style="width:100%;" size="6" id="category" name="category">
                        {% for category in form.category.choices %}
                            <option value="{{ category.name }}">{{ category.value }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Description: </label>
                <div class="form-floating mb-3">
                    <textarea style="white-space: normal" class="form-control rounded-0" name="description" id="description" placeholder="description" rows="10"></textarea>
                </div>
                <div class="col-6 mx-auto">
                    <input type="file" name="file" id="file" multiple="multiple">
                </div>
                <div class="form-floating mb-3">
                    <input type="text" name="connection" class="form-control" id="connection" placeholder="connection">
                    <label for="connection">Connection</label>
                </div>
                </div>

                <button class="w-100 btn btn-lg btn-primary" type="submit">Create</button>
            </form>
        </div>
    </div>

{% endblock %}

application/templates/ad/edit_ad.html
{% extends "layout.html" %}

{% block content %}

    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <h1 class="h3 mb-3 fw-normal text-center">Edit your ad</h1>

                <div class="form-floating mb-3">
                    <input value="{{ ad.title }}" type="text" name="title" class="form-control" id="title" placeholder="title">
                    <label for="title">Title</label>
                </div>

                  <div class="form-floating mb-3">
                    <select style="width:100%;" size="6" id="category" name="category">
                        {% for category in form.category.choices %}
                            {% if category == ad.category %}
                                <option value="{{ category.name }}" selected>{{ category.value }}</option>
                            {% else %}
                                <option value="{{ category.name }}">{{ category.value }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Description: </label>
                <div class="form-floating mb-3">
                    <textarea style="white-space: normal" class="form-control rounded-0" name="description" id="description" placeholder="description" rows="10">
                        {{ ad.description }}
                    </textarea>
                </div>
                <div class="col-6 mx-auto">
                    <p>Add photo: </p>
                    <input type="file" name="file" id="file" multiple="multiple">
                    <p></p>
                </div>

                <div class="form-floating mb-3">
                    <input type="text" value="{{ ad.connection }}" name="connection" class="form-control" id="connection" placeholder="connection">
                    <label for="connection">Title</label>
                </div>

                <div>
                    {% for photo in ad.ad_photos %}
                        <img src="{{ url_for('static', filename = photo.link) }}" alt="" width=50% height=50%>
                        <a type="button" class="btn btn-outline-danger" href="{{ url_for('ad.delete_ad_photo', link_id=photo.id) }}">Delete</a>
                        <p></p>
                    {% endfor %}
                </div>

                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Edit</button>
            </form>
        </div>
    </div>

{% endblock %}

application/templates/ad/photo.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Upload</title>
</head>
<body>
    <div class="col-6 mx-auto">
    <form class="form-inline my-2 my-lg-0" action="" method="POST" enctype="multipart/form-data">
        <input type="file" name="file" id="file" multiple="multiple">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
    </form>
    </div>
</body>
</html>

application/templates/ad/show_ad.html
{% extends "layout.html" %}

{% block content %}

        <div class="col-6 mx-auto">
        <p>Title: {{ ad.title }}</p>
        <p>Category: {{ ad.category.value }}</p>
        <p>Description: {{ ad.description }}</p>
        <p>Author: {{ user.username }}</p>
        <p>Connection: {{ ad.connection }}</p>
        {%  for photo in photos %}
            <img src="{{ url_for('static', filename = photo.link) }}" alt="" width=50% height=50%>
            <p></p>
        {%  endfor %}
        {% if user.id == current_user.id %}
            <a type="button" class="btn btn-outline-primary" href="{{ url_for('ad.edit_ad', ad_id=ad.id) }}">Edit</a>
            <a type="button" class="btn btn-outline-danger" href="{{ url_for('ad.delete_ad', ad_id=ad.id) }}">Delete</a>
        {% endif %}

        </div>

{% endblock %}