application/ad/routes.py
import os

from flask import Blueprint
from flask_login import login_required

import application.ad.controller as controller
from application.admin import is_owner

template_dir = os.path.abspath('../templates')
ad_blueprint = Blueprint('ad', __name__, url_prefix='/ad', template_folder=template_dir)


@ad_blueprint.route('/create-ad', methods=['GET', 'POST'])
@login_required
def create_ad():
    return controller.create_ad()


@ad_blueprint.route('/<ad_id>')
@login_required
def show_ad(ad_id):
    return controller.show_ad(ad_id)


@ad_blueprint.route('/<ad_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_ad(ad_id):
    return controller.edit_ad(ad_id)


@ad_blueprint.route('/<ad_id>/delete')
@login_required
def delete_ad(ad_id):
    return controller.delete_ad(ad_id)


@ad_blueprint.route('/<link_id>/delete_ad_photo')
@login_required
def delete_ad_photo(link_id):
    return controller.delete_ad_photo(link_id)

application/main/routes.py
import os

from flask import Blueprint, render_template, request

from application.models import Ad
from application.models import Categories


template_dir = os.path.abspath('../templates')
main_blueprint = Blueprint('main', __name__, template_folder=template_dir)


@main_blueprint.route('/')
def index():
    search = request.args.get('search')
    categories = request.args.getlist('category')
    page = request.args.get('page')
    ads = Ad.query.order_by(Ad.created_at.desc())
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if search:
        found = "%{}%".format(search)
        ads = Ad.query.filter(
            Ad.title.like(found) |
            Ad.category.like(found) |
            Ad.description.like(found)
        ).order_by(Ad.created_at.desc())

    if categories:
        ads = Ad.query.filter(
            Ad.category.in_(categories)
        )
    pages = ads.paginate(page=page, per_page=5)

    return render_template('main/main.html', title='Index',
                           ads=ads, categoryes=Categories, pages=pages)

application/templates/main/main.html
{% extends "layout.html" %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form style="display: flex; width:25%"  class="form-inline my-2 my-lg-0">
        <input style="width: 100%" class="form-control mr-sm-2" type="search" placeholder="Search ad" aria-label="Search" name="search" value="{{ request.args.get('search', '') }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <br>

    <form class="form-inline my-2 my-lg-0">
        {% for category in categoryes %}
            <input type="checkbox" id="category" name="category" value="{{ category.name }}">{{ category.value }}
        {% endfor %}
        <br>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
    </form>

    {% for ad in pages.items %}
        <a href="{{ url_for('ad.show_ad', ad_id=ad.id) }}">{{ ad.title }}</a>
        <p>{{ ad.category.value }}</p>
        <p>{{ ad.description }}</p>
        {% for photo in ad.ad_photos %}
            <img src="{{ url_for('static', filename = photo.link) }}" alt="" width=20% height=20%>
        {% endfor %}
        <hr>
    {% endfor %}
<nav>
  <ul class="pagination">
      <li {% if pages.has_prev %}>
          <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
          </a>
          {% else %}
          <a class="page-link" href="" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
          </a>
          {% endif %}
      </li>

        {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %} class="active" {% endif %}>
                <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}

        <li {% if pages.has_next %}>
          <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
              <span class="sr-only">Next</span>
              <span aria-hidden="true">&raquo;</span>
          </a>

          {% else %}
          <a class="page-link" href="" aria-label="Next">
              <span class="sr-only">Next</span>
              <span aria-hidden="true">&raquo;</span>
          </a>
          {% endif %}
        </li>
  </ul>
</nav>
</body>
</html>
{% endblock %}